config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new', as: :login
  get 'auth/salesforce/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :leads do
    post '/salesforce' => 'leads#salesforce' , on: :member
  end
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  validates_presence_of :name, :last_name, :email, :company, :job_title, :phone, :website
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :uid, :access_token, :instance_url

  def self.create_with_salesforce(auth)
    create! do |user|
      user.email = auth['extra']['email']
      user.uid = auth['uid']
      user.access_token = auth['credentials']['token']
      user.instance_url = auth['credentials']['instance_url']
    end
  end

  def credentials
    { token: access_token, instance_url: instance_url }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    return if session[:user_id] && current_user
    redirect_to login_path
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_filter :authenticate!

  def index
    @leads = Lead.all
  end

  def show
    @lead = Lead.find(params[:id])
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)

    if @lead.save
      flash[:success] = 'Lead criado com sucesso!'
      redirect_to leads_path
    else
      render action: :new
    end
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def update
    @lead = Lead.find(params[:id])

    if @lead.update_attributes(lead_params)
      flash[:success] = 'Lead atualizado com sucesso!'
      redirect_to leads_path
    else
      render action: :edit
    end
  end

  def destroy
    @lead = Lead.find(params[:id])

    if @lead.destroy
      flash[:success] = 'Lead apagado!'
      redirect_to leads_path
    else
      render action: :index
    end
  end

  def salesforce
    @lead = Lead.find(params[:id])
    salesforce_lead = Salesforce::Lead.new(@lead.attributes.symbolize_keys, current_user.credentials)

    if salesforce_lead.create
      flash[:success] = 'Lead adicionado ao Salesforce com successo!'
      redirect_to leads_path
    else
      flash[:error] = salesforce_lead.errors.map{ |e| e[:message] }.join(', ')
      redirect_to leads_path
    end
  end

  private
  def lead_params
    params.require(:lead).permit(:name, :last_name, :email, :company, :job_title, :phone, :website)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to leads_path if current_user
  end

  def create
    auth = request.env['omniauth.auth']
    user = User.find_by(uid: auth['uid']) || User.create_with_salesforce(auth)
    session[:user_id] = user.id
    redirect_to leads_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lead Manager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav>
        <% if current_user %>
          Olá, <%= current_user.email %>!
          <%= link_to 'Sair', logout_path %>
        <% end %>
      </nav>
      <section>
        <% unless flash[:error].blank? %>
          <div class='flash-error'><%= flash[:error].html_safe %></div>
        <% end %>

        <% unless flash[:success].blank? %>
          <div class='flash-success'><%= flash[:success].html_safe %></div>
        <% end %>
      </section>
    </header>
    <section>
      <%= yield %>
    </section>
  </body>
</html>

app/views/leads/_form.html.erb
<%= render partial: 'shared/validation_errors', locals: { object: @lead } %>

<dt>Nome</dt>
<dd><%= f.text_field :name %></dd>

<dt>Sobrenome</dt>
<dd><%= f.text_field :last_name %></dd>

<dt>Email</dt>
<dd><%= f.email_field :email %></dd>

<dt>Empresa</dt>
<dd><%= f.text_field :company %></dd>

<dt>Cargo</dt>
<dd><%= f.text_field :job_title %></dd>

<dt>Telefone</dt>
<dd><%= f.phone_field :phone %></dd>

<dt>Site</dt>
<dd><%= f.url_field :website %></dd>

<%= submit_tag 'salvar' %>

app/views/leads/_lead.html.erb
<p><%= link_to lead.name, lead_path(lead) %> </p>

<%= link_to 'editar', edit_lead_path(lead) %>
<%= link_to 'deletar', lead_path(lead), method: :delete, data: { confirm: 'Tem certeza que deseja apagar esse Lead?' }, class: 'delete' %>
<%= link_to 'adicionar ao Salesforce', salesforce_lead_path(lead), method: :post %>

app/views/leads/edit.html.erb
Editar

<%= form_for @lead, url: lead_path(@lead) do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/leads/index.html.erb
<h3>Leads</h3>

<% if @leads.empty? %>
  <p> Não existem leads cadastradas. </p>
<% else %>
  <%= render @leads %>
<% end %>

<br />

<%= link_to 'Novo', new_lead_path %>

app/views/leads/new.html.erb
Novo

<%= form_for @lead, url: leads_path do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/leads/show.html.erb
<p>Nome: <%= @lead.name %> </p>
<p>Sobrenome: <%= @lead.last_name %> </p>
<p>Email: <%= @lead.email %> </p>
<p>Empresa: <%= @lead.company %> </p>
<p>Cargo: <%= @lead.job_title %> </p>
<p>Telefone: <%= @lead.phone %> </p>
<p>Site: <%= @lead.website %> </p>

app/views/shared/_validation_errors.html.erb
<% unless object.errors.empty? %>
  <% object.errors.full_messages.each do |error| %>
    <p class='validation-error'><%= error %></p>
  <% end %>
<% end %>